### ISSUE TITLE
Maintain one master branch

### ISSUE THREAD

**Issue by atinmu** [microsoft/lisa#1320]
Now that LisaV3 is almost ready to rock, can we not merge both v2 (master) and v3 (main) branches into one master branch to avoid any confusion. I understand that some of the tests/infra from v2 are to be still used as there's no benefit of porting them into v3, but to avoid developers getting confused with managing multiple branches, we can just simply maintain the code (with separate folders as v2 & v3) in one branch. Also till date all the latest from master can be branched out as lisav2 to retain the history.
Thoughts?

**Comment by glima** [comment]
I never liked the fact that they live in the same repo. The same folder will be even more mind-blowing, I'd vote no. Why not migrate to a new repo?

**Comment by squirrelsc** [comment]
The v2 is still playing an important role in validation, and it will be retired step by step. Because we want to leverage the same name and branding of LISA, so they are in the same repo. Yes, it's confusing to host two different codebase in same repo, but it's also confusing that if we bring two codebase into the same repo. Hope we can migrate to v3 sooner, to mitigate it.
I will close this issue. Feel free to let me know, if there are further questions.

**Comment by atinmu** [comment]
Since you folks understand the code structure of both the versions better than me, certainly you would be able to evaluate this better however as a developer if one has to touch upon multiple versions of a functionality to introduce/enhance a feature (for eg - a feature which brings in a change in framework (in v3) and respective changes in some tests (in v2)) PRs need to be raised in multiple branches which can look bit of uncomfort and confusing to few devs. Just my 2 cents.

**Comment by squirrelsc** [comment]
Thank you for raising points. Yes, we need to manage dependencies, if this case happens. As current observation, it happens seldom. Its cost is much lower than merging them and fix all pipelines.
