### ISSUE TITLE
XML global config file contains sensitive information after the run is complete

### ISSUE THREAD

**Issue by ader1990** [microsoft/lisa#148]
After a LISAv2 run with secrets file path given as a parameter, XML\GlobalConfigurations.xml contains the secrets and it may leak sensitive information.

Possible fix: create a copy of the existing XML\GlobalConfigurations.xml and revert the XML\GlobalConfigurations.xml contents to the initial copy at the end of the lisav2 run.

**Comment by chvalean** [comment]
@juhlee-microsoft please advise on the priority to fix this.

LE: this has been confirmed and requires fix.

**Comment by lizzha** [comment]
In current LISAv2 code, GlobalConfigurations.xml is loaded to memory once and then config is updated in memory and written back to the file on disk. But the file will not be read again after being changed. So we can just don't write back the updated global config to the GlobalConfigurations.xml file, so that it keeps unchanged.
@LiliDeng could you please make this change and validate it ASAP?
