### ISSUE TITLE
custom parameter for extra verification in VM provisionining

### ISSUE THREAD

**Issue by juhlee-microsoft** [microsoft/lisa#438]
Recently new VM size test requirement demands the number of vCPU and memory size verification. The VM provision test 'VERIFY-DEPLOYMENT-PROVISION' can take a custom parameter 'vCPU''. If any parameter is set in CustomParameter section in LISAv2, the test will verify the number of vCPU.

**Comment by chvalean** [comment]
Script: https://github.com/LIS/LISAv2/blob/master/Testscripts/Windows/VERIFY-DEPLOYMENT-PROVISION.ps1

Assigning this to @stefanlupsa

**Comment by stefanlupsa** [comment]
@juhlee-microsoft I've done some testing with this and vMem never matches what the VM sees, i don't know of a better way to get the memory inside the vm other than `grep MemTotal /proc/meminfo` but this never matches the exact amount the VM is supposed to have either in HyperV or Azure. Can you please clarify what is to be done?

**Comment by chvalean** [comment]
I don't think a check to memory is possible, due to the variations in actual size, plus the old discussion on how the linux kernel reserves for mapping the memory.

An example is that for Size: Standard D12 v2 (4 vcpus, 28 GiB memory), meminfo shows a total of
MemTotal:       28776524 kB
which is over 28.7 GB of memory.

So we never have a good mapping of allocated vs what the VM reports, to do a perfect match.

**Comment by juhlee-microsoft** [comment]
@stefanlupsa @chvalean I understand the problem here, and I will change the requirement to vCPU only. At least we capture it from the VM name.
