### ISSUE TITLE
HYPERV - Add try catch in method Get-HostMemory

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#526]
Need add try catch in https://github.com/LIS/LISAv2/blob/master/Libraries/HyperV.psm1#L901
Hit below exception -
```
08/21/2019 07:28:20 : [INFO ] HyperV Group LISAv2-TwoVM-lili-SB60-637019441004 Created with Instance ID: da702593-ffff-40c4-a561-a6d0cefc0fb0.
08/21/2019 07:28:21 : [INFO ] Checking if there is enough memory on localhost
08/21/2019 07:28:21 : [ERROR] Exception detected. Source : DeployVMs()
08/21/2019 07:28:21 : [ERROR] EXCEPTION : Cannot index into a null array.
08/21/2019 07:28:21 : [ERROR] Source : Line 904 in script .\Libraries\HyperV.psm1.
08/21/2019 07:28:21 : [INFO ] CURRENT - PASS    - 0
08/21/2019 07:28:21 : [INFO ] CURRENT - SKIPPED - 0
08/21/2019 07:28:21 : [INFO ] CURRENT - FAIL    - 0
08/21/2019 07:28:21 : [INFO ] CURRENT - ABORTED - 4
08/21/2019 07:28:21 : [INFO ] Test SB60 finished
```

**Comment by xian123** [comment]
Add try...catch statement cannot resolve this issue. The root cause is that the return value of Get-Counter is null if $HvServer is offline. Index into a null array is prohibited.

$availableMemory = [int](Get-Counter -Counter "\Memory\Available MBytes" -ComputerName $HvServer).CounterSamples[0].CookedValue

**Comment by xian123** [comment]
This patch [#532](https://github.com/LIS/LISAv2/pull/532) fixed the issue.
